- name: Ensure {{ github_actions_runner_group }} group created
  group:
    name: "{{ github_actions_runner_group }}"
    state: present

- name: Ensure {{ github_actions_runner_user }} user created
  user:
    name: "{{ github_actions_runner_user }}"
    state: present
    shell: /bin/bash
    password: "{{ github_actions_runner_user | password_hash('sha512','A512') }}"
    group: "{{ github_actions_runner_group }}"
