# - fail: msg="Bailing out: this play requires 'github_pat'"
#   when: github_pat == ""

# - fail: msg="Bailing out: this play requires 'github_organization'"
#   when: github_organization == ""

# Installing prerequisite packages
- name: Installing prerequisite packages
  apt:
    name:
      - "curl"
      - "jq"
    state: present
    update_cache: yes

# Create github user
- include_tasks: github-user.yml

# Download scripts
- name: Download "Automate Configuring Self-Hosted Runners" scripts
  ansible.builtin.get_url:
    url: "{{ github_actions_runner_url }}/{{ item.in }}"
    dest: "{{ github_actions_runner_bootstrap_user_home }}/{{ item.out }}"
    mode: '0755'
  loop: "{{ github_actions_runner_scripts }}"

# Create self-hosted runner
- include_tasks: runner-create.yml
  when: github_actions_runner_mode == 'create'

# Remove self-hosted runner
- include_tasks: runner-remove.yml
  when: github_actions_runner_mode == 'remove'
