- name: Automate Configuring Self-Hosted Runners
  args:
    executable: /bin/bash
    chdir: "{{ github_actions_runner_install_dir }}"
    creates: "{{ github_actions_runner_install_dir }}/runner"
  environment:
    RUNNER_CFG_PAT: "{{ github_pat }}"
  ansible.builtin.shell: |
      ./create-latest-svc.sh \
        -s {{ github_organization }} \
        -u {{ github_actions_runner_user }}
