- name: Removing Self-Hosted Runners
  environment:
    RUNNER_CFG_PAT: "{{ github_pat }}"
  ansible.builtin.shell: |
    ./runner-remove-svc.sh {{ github_organization }} 
  args:
    executable: /bin/bash
    chdir: "{{ github_actions_runner_user_home }}"
  ignore_errors: true
